version: '3.7'

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DATABASENAME}
      MONGO_INITDB_ROOT_USERNAME: ${ROOTUSER}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOTPASS}
    command: mongod --quiet --logpath /dev/null 

  web:
    build: .
    # command: ["npm", "test"]
    command: ["npm", "start"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOTUSER}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOTPASS}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - "db"